// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gQgwwv8triFQkCLHHJpBYNxPAvc2RpY',
    appId: '1:424722169578:web:5c24d523234ab0f533e193',
    messagingSenderId: '424722169578',
    projectId: 'flutter-chat-app-e031a',
    authDomain: 'flutter-chat-app-e031a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e031a.appspot.com',
    measurementId: 'G-EM5BGSFPCB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOYkOpPO7Ttlr8TGpgPOhurh0fSdhoEk',
    appId: '1:424722169578:ios:985e1044703921cb33e193',
    messagingSenderId: '424722169578',
    projectId: 'flutter-chat-app-e031a',
    storageBucket: 'flutter-chat-app-e031a.appspot.com',
    iosClientId: '424722169578-riq5m78d96tnaicqc4ju85giil9hja42.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOYkOpPO7Ttlr8TGpgPOhurh0fSdhoEk',
    appId: '1:424722169578:ios:2f8c5a94ab07336933e193',
    messagingSenderId: '424722169578',
    projectId: 'flutter-chat-app-e031a',
    storageBucket: 'flutter-chat-app-e031a.appspot.com',
    iosClientId: '424722169578-v6c7m0cvdjstcoj59je5uvinovcc81hd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
